package yd;

import fI.C17221b;
import kotlin.Metadata;

@Metadata(d1 = {"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0010\u000e\n\u0002\bD\b\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001B\u0011\b\u0002\u0012\u0006\u0010\u0003\u001a\u00020\u0002¢\u0006\u0004\b\u0004\u0010\u0005R\u0017\u0010\u0003\u001a\u00020\u00028\u0006¢\u0006\f\n\u0004\b\u0003\u0010\u0006\u001a\u0004\b\u0007\u0010\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bE¨\u0006F"}, d2 = {"Lyd/J;", "", "", "value", "<init>", "(Ljava/lang/String;ILjava/lang/String;)V", "Ljava/lang/String;", "b", "()Ljava/lang/String;", "POI_SUBTYPE_ENTRANCE", "POI_SUBTYPE_ENTRANCE_EXIT", "POI_SUBTYPE_SHOWROOM_ENTRANCE", "POI_SUBTYPE_MARKETHALL_ENTRANCE", "POI_SUBTYPE_EXIT", "POI_SUBTYPE_STAIRS", "POI_SUBTYPE_ESCALATOR", "POI_SUBTYPE_ESCALATOR_UP", "POI_SUBTYPE_ESCALATOR_DOWN", "POI_SUBTYPE_LIFT", "POI_SUBTYPE_LIFT_UP", "POI_SUBTYPE_LIFT_DOWN", "POI_SUBTYPE_CHECK_OUT", "POI_SUBTYPE_RESTAURANT_AND_CAFE", "POI_SUBTYPE_BISTRO", "POI_SUBTYPE_CAFE", "POI_SUBTYPE_RESTROOM", "POI_SUBTYPE_ACCESSIBLE_RESTROOM", "POI_SUBTYPE_RESTROOM_WOMAN", "POI_SUBTYPE_RESTROOM_MAN", "POI_SUBTYPE_RESTROOM_WITH_CHANGING_TABLE", "POI_SUBTYPE_NURSING_ROOM", "POI_SUBTYPE_SHOPPING_TROLLEY", "POI_SUBTYPE_FURNITURE_TROLLEY", "POI_SUBTYPE_BABY_STROLLER", "POI_SUBTYPE_KIOSK_OR_DISPLAY", "POI_SUBTYPE_ATM", "POI_SUBTYPE_INFORMATION", "POI_SUBTYPE_CUSTOMER_SERVICE", "POI_SUBTYPE_IKEA_FAMILY", "POI_SUBTYPE_EXCHANGES_AND_RETURNS", "POI_SUBTYPE_PLANNING_AND_CONSULTATION", "POI_SUBTYPE_PICK_UP_POINT", "POI_SUBTYPE_DELIVERY_SERVICES", "POI_SUBTYPE_LOCKERS", "POI_SUBTYPE_SPARE_PARTS", "POI_SUBTYPE_RECYCLE_STATION", "POI_SUBTYPE_BUS_STOP", "POI_SUBTYPE_TAXI_STOP", "POI_SUBTYPE_TRAIN_STATION", "POI_SUBTYPE_PARKING", "POI_SUBTYPE_PARKING_GARAGE", "POI_SUBTYPE_IKEA_FOR_BUSINESS", "POI_SUBTYPE_CIRCULAR_HUB", "POI_SUBTYPE_SWEDISH_FOOD_MARKET", "POI_SUBTYPE_SMALAND", "POI_SUBTYPE_FINANCIAL_DESK", "POI_SUBTYPE_PLANNER_KITCHEN", "POI_SUBTYPE_PLANNER_BEDROOM", "POI_SUBTYPE_PLANNER_LIVING_ROOM", "POI_SUBTYPE_INSPIRATIONAL", "POI_SUBTYPE_PAYMENT_POINT", "POI_SUBTYPE_CHRISTMAS_MARKET", "POI_SUBTYPE_ACTIVITY_AREA_0", "POI_SUBTYPE_ACTIVITY_AREA_1", "POI_SUBTYPE_ACTIVITY_AREA_2", "POI_SUBTYPE_ACTIVITY_AREA_3", "POI_SUBTYPE_ACTIVITY_AREA_4", "POI_SUBTYPE_ACTIVITY_AREA_5", "POI_SUBTYPE_ACTIVITY_AREA_6", "POI_SUBTYPE_ACTIVITY_AREA_7", "KompassMap_release"}, k = 1, mv = {2, 0, 0}, xi = 48)
/* renamed from: yd.J  reason: case insensitive filesystem */
public enum C10439J {
    POI_SUBTYPE_ENTRANCE("POI_SUBTYPE_ENTRANCE"),
    POI_SUBTYPE_ENTRANCE_EXIT("POI_SUBTYPE_ENTRANCE_EXIT"),
    POI_SUBTYPE_SHOWROOM_ENTRANCE("POI_SUBTYPE_SHOWROOM_ENTRANCE"),
    POI_SUBTYPE_MARKETHALL_ENTRANCE("POI_SUBTYPE_MARKETHALL_ENTRANCE"),
    POI_SUBTYPE_EXIT("POI_SUBTYPE_EXIT"),
    POI_SUBTYPE_STAIRS("POI_SUBTYPE_STAIRS"),
    POI_SUBTYPE_ESCALATOR("POI_SUBTYPE_ESCALATOR"),
    POI_SUBTYPE_ESCALATOR_UP("POI_SUBTYPE_ESCALATOR_UP"),
    POI_SUBTYPE_ESCALATOR_DOWN("POI_SUBTYPE_ESCALATOR_DOWN"),
    POI_SUBTYPE_LIFT("POI_SUBTYPE_LIFT"),
    POI_SUBTYPE_LIFT_UP("POI_SUBTYPE_LIFT_UP"),
    POI_SUBTYPE_LIFT_DOWN("POI_SUBTYPE_LIFT_DOWN"),
    POI_SUBTYPE_CHECK_OUT("POI_SUBTYPE_CHECK_OUT"),
    POI_SUBTYPE_RESTAURANT_AND_CAFE("POI_SUBTYPE_RESTAURANT_AND_CAFE"),
    POI_SUBTYPE_BISTRO("POI_SUBTYPE_BISTRO"),
    POI_SUBTYPE_CAFE("POI_SUBTYPE_CAFE"),
    POI_SUBTYPE_RESTROOM("POI_SUBTYPE_RESTROOM"),
    POI_SUBTYPE_ACCESSIBLE_RESTROOM("POI_SUBTYPE_ACCESSIBLE_RESTROOM"),
    POI_SUBTYPE_RESTROOM_WOMAN("POI_SUBTYPE_RESTROOM_WOMAN"),
    POI_SUBTYPE_RESTROOM_MAN("POI_SUBTYPE_RESTROOM_MAN"),
    POI_SUBTYPE_RESTROOM_WITH_CHANGING_TABLE("POI_SUBTYPE_RESTROOM_WITH_CHANGING_TABLE"),
    POI_SUBTYPE_NURSING_ROOM("POI_SUBTYPE_NURSING_ROOM"),
    POI_SUBTYPE_SHOPPING_TROLLEY("POI_SUBTYPE_SHOPPING_TROLLEY"),
    POI_SUBTYPE_FURNITURE_TROLLEY("POI_SUBTYPE_FURNITURE_TROLLEY"),
    POI_SUBTYPE_BABY_STROLLER("POI_SUBTYPE_BABY_STROLLER"),
    POI_SUBTYPE_KIOSK_OR_DISPLAY("POI_SUBTYPE_KIOSK_OR_DISPLAY"),
    POI_SUBTYPE_ATM("POI_SUBTYPE_ATM"),
    POI_SUBTYPE_INFORMATION("POI_SUBTYPE_INFORMATION"),
    POI_SUBTYPE_CUSTOMER_SERVICE("POI_SUBTYPE_CUSTOMER_SERVICE"),
    POI_SUBTYPE_IKEA_FAMILY("POI_SUBTYPE_IKEA_FAMILY"),
    POI_SUBTYPE_EXCHANGES_AND_RETURNS("POI_SUBTYPE_EXCHANGES_AND_RETURNS"),
    POI_SUBTYPE_PLANNING_AND_CONSULTATION("POI_SUBTYPE_PLANNING_AND_CONSULTATION"),
    POI_SUBTYPE_PICK_UP_POINT("POI_SUBTYPE_PICK_UP_POINT"),
    POI_SUBTYPE_DELIVERY_SERVICES("POI_SUBTYPE_DELIVERY_SERVICES"),
    POI_SUBTYPE_LOCKERS("POI_SUBTYPE_LOCKERS"),
    POI_SUBTYPE_SPARE_PARTS("POI_SUBTYPE_SPARE_PARTS"),
    POI_SUBTYPE_RECYCLE_STATION("POI_SUBTYPE_RECYCLE_STATION"),
    POI_SUBTYPE_BUS_STOP("POI_SUBTYPE_BUS_STOP"),
    POI_SUBTYPE_TAXI_STOP("POI_SUBTYPE_TAXI_STOP"),
    POI_SUBTYPE_TRAIN_STATION("POI_SUBTYPE_TRAIN_STATION"),
    POI_SUBTYPE_PARKING("POI_SUBTYPE_PARKING"),
    POI_SUBTYPE_PARKING_GARAGE("POI_SUBTYPE_PARKING_GARAGE"),
    POI_SUBTYPE_IKEA_FOR_BUSINESS("POI_SUBTYPE_IKEA_FOR_BUSINESS"),
    POI_SUBTYPE_CIRCULAR_HUB("POI_SUBTYPE_CIRCULAR_HUB"),
    POI_SUBTYPE_SWEDISH_FOOD_MARKET("POI_SUBTYPE_SWEDISH_FOOD_MARKET"),
    POI_SUBTYPE_SMALAND("POI_SUBTYPE_SMALAND"),
    POI_SUBTYPE_FINANCIAL_DESK("POI_SUBTYPE_FINANCIAL_DESK"),
    POI_SUBTYPE_PLANNER_KITCHEN("POI_SUBTYPE_PLANNER_KITCHEN"),
    POI_SUBTYPE_PLANNER_BEDROOM("POI_SUBTYPE_PLANNER_BEDROOM"),
    POI_SUBTYPE_PLANNER_LIVING_ROOM("POI_SUBTYPE_PLANNER_LIVING_ROOM"),
    POI_SUBTYPE_INSPIRATIONAL("POI_SUBTYPE_INSPIRATIONAL"),
    POI_SUBTYPE_PAYMENT_POINT("POI_SUBTYPE_PAYMENT_POINT"),
    POI_SUBTYPE_CHRISTMAS_MARKET("POI_SUBTYPE_CHRISTMAS_MARKET"),
    POI_SUBTYPE_ACTIVITY_AREA_0("POI_SUBTYPE_ACTIVITY_AREA_0"),
    POI_SUBTYPE_ACTIVITY_AREA_1("POI_SUBTYPE_ACTIVITY_AREA_1"),
    POI_SUBTYPE_ACTIVITY_AREA_2("POI_SUBTYPE_ACTIVITY_AREA_2"),
    POI_SUBTYPE_ACTIVITY_AREA_3("POI_SUBTYPE_ACTIVITY_AREA_3"),
    POI_SUBTYPE_ACTIVITY_AREA_4("POI_SUBTYPE_ACTIVITY_AREA_4"),
    POI_SUBTYPE_ACTIVITY_AREA_5("POI_SUBTYPE_ACTIVITY_AREA_5"),
    POI_SUBTYPE_ACTIVITY_AREA_6("POI_SUBTYPE_ACTIVITY_AREA_6"),
    POI_SUBTYPE_ACTIVITY_AREA_7("POI_SUBTYPE_ACTIVITY_AREA_7");
    
    private final String value;

    static {
        C10439J[] a10;
        $ENTRIES = C17221b.a(a10);
    }

    private C10439J(String str) {
        this.value = str;
    }

    public final String b() {
        return this.value;
    }
}
