package E8;

import kotlin.Metadata;

@Metadata(d1 = {"\u0000\u0010\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0010\u000b\n\u0002\b;\b\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001B\u0013\b\u0002\u0012\b\b\u0002\u0010\u0003\u001a\u00020\u0002¢\u0006\u0004\b\u0004\u0010\u0005R\u0017\u0010\u0003\u001a\u00020\u00028\u0006¢\u0006\f\n\u0004\b\u0003\u0010\u0006\u001a\u0004\b\u0007\u0010\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<¨\u0006="}, d2 = {"LE8/b;", "", "", "isGdpr", "<init>", "(Ljava/lang/String;IZ)V", "Z", "b", "()Z", "CLIENT_MODE_ACTIVATION_STATE", "CLIENT_MODE_LONG_SNAPSHOT_SCROLL_DELAY_MILLISECONDS", "CLIENT_MODE_SCREENGRAPH_OPTIMIZATION_MODE", "LOCAL_SESSION_REPLAY_MODE", "LOCAL_LOG_VISUALIZER_MODE", "CLIENT_MODE_TUTORIAL", "USER_ID", "INAPP_USER_ID", "SESSION_ID", "SCREEN_NUMBER", "PAUSED_SESSION_ID", "PAUSED_SCREEN_NUMBER", "SCREEN_TIMESTAMP", "DEVELOPER_MODE_ACTIVATION_STATE", "SESSION_REPLAY_GET_REPLAY_LINK", "SESSION_REPLAY_FORCE_START", "SESSION_REPLAY_DEFAULT_MASKING", "SESSION_REPLAY_ETR_ENABLED", "DEVELOPER_SESSION_REPLAY_FORCE_QUALITY_LEVEL", "DEVELOPER_SESSION_REPLAY_FORCE_ANIMATION_DETECTION", "DEVELOPER_SESSION_REPLAY_LOG_VIEWLIGHT_TREE", "DEVELOPER_SESSION_REPLAY_IMAGE_QUALITY_VALUE", "DEVELOPER_SESSION_REPLAY_FPS_VALUE", "DEVELOPER_SESSION_REPLAY_MAXIMUM_USAGE_ON_UI_THREAD_IN_MILLI_SEC", "DEVELOPER_SESSION_REPLAY_URL", "DEVELOPER_SESSION_REPLAY_PRESET_URL", "DEVELOPER_SESSION_TIMEOUT_TO_0", "DEVELOPER_OVERRIDE_FEATURE_FLAGS_ENABLED", "DEVELOPER_OVERRIDE_FEATURE_FLAGS_STATES", "TRACKING_ENABLE", "FORGET_ME", "PAUSE_TRACKING", "VERBOSE_LOG", "RECORDING_SEGMENT_SAMPLE", "RECORDING_RATE_CONFIG", "RAW_CONFIGURATION_AS_JSON", "TELEMETRY_IS_REPORT_SENT", "TELEMETRY_IS_FORCED_REPORT_SENT", "LONG_SNAPSHOT_EXPLANATION_SHOWN", "TELEMETRY_CUSTOMER_APP_CODE_VERSION", "TELEMETRY_LAST_REPORT_SENT_TIME_STAMP", "TELEMETRY_NETWORK_MONITORING_RATE", "TELEMETRY_PUBLIC_USAGE_RATE", "LAST_APP_VERSION_NUMBER", "LAST_SDK_VERSION_NUMBER", "IS_MIGRATED_FROM_PREFS_HELPER", "LAST_SEGMENT", "IS_TRACKABLE", "IS_OPT_OUT", "LAST_EVENT_TIMESTAMP", "IS_HIDE_EVENT_PENDING", "SCHEDULED_APP_HIDE_EVENT", "core_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
public enum b {
    CLIENT_MODE_ACTIVATION_STATE(false, 1, (boolean) null),
    CLIENT_MODE_LONG_SNAPSHOT_SCROLL_DELAY_MILLISECONDS(false, 1, (boolean) null),
    CLIENT_MODE_SCREENGRAPH_OPTIMIZATION_MODE(false, 1, (boolean) null),
    LOCAL_SESSION_REPLAY_MODE(false, 1, (boolean) null),
    LOCAL_LOG_VISUALIZER_MODE(false, 1, (boolean) null),
    CLIENT_MODE_TUTORIAL(false, 1, (boolean) null),
    USER_ID(true),
    INAPP_USER_ID(false, 1, (boolean) null),
    SESSION_ID(true),
    SCREEN_NUMBER(true),
    PAUSED_SESSION_ID(true),
    PAUSED_SCREEN_NUMBER(true),
    SCREEN_TIMESTAMP(false, 1, (boolean) null),
    DEVELOPER_MODE_ACTIVATION_STATE(false, 1, (boolean) null),
    SESSION_REPLAY_GET_REPLAY_LINK(false, 1, (boolean) null),
    SESSION_REPLAY_FORCE_START(false, 1, (boolean) null),
    SESSION_REPLAY_DEFAULT_MASKING(false, 1, (boolean) null),
    SESSION_REPLAY_ETR_ENABLED(false, 1, (boolean) null),
    DEVELOPER_SESSION_REPLAY_FORCE_QUALITY_LEVEL(false, 1, (boolean) null),
    DEVELOPER_SESSION_REPLAY_FORCE_ANIMATION_DETECTION(false, 1, (boolean) null),
    DEVELOPER_SESSION_REPLAY_LOG_VIEWLIGHT_TREE(false, 1, (boolean) null),
    DEVELOPER_SESSION_REPLAY_IMAGE_QUALITY_VALUE(false, 1, (boolean) null),
    DEVELOPER_SESSION_REPLAY_FPS_VALUE(false, 1, (boolean) null),
    DEVELOPER_SESSION_REPLAY_MAXIMUM_USAGE_ON_UI_THREAD_IN_MILLI_SEC(false, 1, (boolean) null),
    DEVELOPER_SESSION_REPLAY_URL(false, 1, (boolean) null),
    DEVELOPER_SESSION_REPLAY_PRESET_URL(false, 1, (boolean) null),
    DEVELOPER_SESSION_TIMEOUT_TO_0(false, 1, (boolean) null),
    DEVELOPER_OVERRIDE_FEATURE_FLAGS_ENABLED(false, 1, (boolean) null),
    DEVELOPER_OVERRIDE_FEATURE_FLAGS_STATES(false, 1, (boolean) null),
    TRACKING_ENABLE(false, 1, (boolean) null),
    FORGET_ME(false, 1, (boolean) null),
    PAUSE_TRACKING(false, 1, (boolean) null),
    VERBOSE_LOG(false, 1, (boolean) null),
    RECORDING_SEGMENT_SAMPLE(false, 1, (boolean) null),
    RECORDING_RATE_CONFIG(false, 1, (boolean) null),
    RAW_CONFIGURATION_AS_JSON(false, 1, (boolean) null),
    TELEMETRY_IS_REPORT_SENT(false, 1, (boolean) null),
    TELEMETRY_IS_FORCED_REPORT_SENT(false, 1, (boolean) null),
    LONG_SNAPSHOT_EXPLANATION_SHOWN(false, 1, (boolean) null),
    TELEMETRY_CUSTOMER_APP_CODE_VERSION(false, 1, (boolean) null),
    TELEMETRY_LAST_REPORT_SENT_TIME_STAMP(false, 1, (boolean) null),
    TELEMETRY_NETWORK_MONITORING_RATE(false, 1, (boolean) null),
    TELEMETRY_PUBLIC_USAGE_RATE(false, 1, (boolean) null),
    LAST_APP_VERSION_NUMBER(false, 1, (boolean) null),
    LAST_SDK_VERSION_NUMBER(false, 1, (boolean) null),
    IS_MIGRATED_FROM_PREFS_HELPER(false, 1, (boolean) null),
    LAST_SEGMENT(true),
    IS_TRACKABLE(true),
    IS_OPT_OUT(false, 1, (boolean) null),
    LAST_EVENT_TIMESTAMP(true),
    IS_HIDE_EVENT_PENDING(true),
    SCHEDULED_APP_HIDE_EVENT(true);
    
    private final boolean isGdpr;

    private b(boolean z10) {
        this.isGdpr = z10;
    }

    public final boolean b() {
        return this.isGdpr;
    }
}
